app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^jobs/$', views.jobs, name='jobs'),
    url(r'^login/$', views.login, name='login'),
]

appcode/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse

from . import views

urlpatterns = [
    url(r'^home/',views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^', include('app.urls', namespace='app')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^robots.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = 'AppCode'
admin.site.site_header = 'AppCode Technology'

course/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/booking/$', views.booking, name='booking'),
    url(r'^(?P<slug>[\w-]+)/quotation/$', views.quotation, name='quotation'),
    url(r'^(?P<slug>[\w-]+)/complete/$', views.complete, name='complete'),
    url(r'^(?P<slug>[\w-]+)/(?P<open_id>[\d]+)/register/$', views.register, name='register'),
]

course/models.py
from django.db import models
from tinymce.models import HTMLField
from taggit.managers import TaggableManager

from app.models import Teacher, Category, Member


def get_course_file(instance, filename):
    return 'upload/course/%s/%s' % (instance.code, filename)


def get_course_outline_file(instance, filename):
    return 'upload/course/%s/outline/%s' % (instance.code, filename)


def get_course_slider_file(instance, filename):
    return 'upload/course/%s/slides/%s' % (instance.course.code, filename)


class Course(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    content = HTMLField(null=True, blank=True)
    promotion = models.CharField(max_length=50, null=True, blank=True)
    remark = models.CharField(max_length=50, null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    teachers = models.ManyToManyField(Teacher, blank=True)
    days = models.IntegerField(default=0)
    hours = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    outline = models.FileField(upload_to=get_course_outline_file, null=True, blank=True)
    image = models.FileField(upload_to=get_course_file, null=True, blank=True)
    published = models.BooleanField(default=True)
    tags = TaggableManager()

    class Meta:
        db_table = 'course'
        verbose_name_plural = 'Course'

    def __unicode__(self):
        return self.name

    def get_course_opens(self):
        return self.courseopen_set.filter(published=True)


class CourseSlider(models.Model):
    course = models.ForeignKey(Course)
    name = models.CharField(max_length=100)
    image = models.FileField(upload_to=get_course_slider_file, null=True, blank=True)

    class Meta:
        db_table = 'course_slider'
        verbose_name_plural = 'CourseSlider'

    def __unicode__(self):
        return self.name


class CourseOption(models.Model):
    course = models.ForeignKey(Course)
    option = models.CharField(max_length=50)

    class Meta:
        db_table = 'course_option'
        verbose_name_plural = 'CourseOption'

    def __unicode__(self):
        return self.option


class CourseOpen(models.Model):
    course = models.ForeignKey(Course)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=150, null=True, blank=True)
    times = models.CharField(max_length=50, null=True, blank=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    promotion = models.CharField(max_length=50, null=True, blank=True)
    published = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)

    class Meta:
        db_table = 'course_open'
        verbose_name_plural = 'CourseOpen'

    def __unicode__(self):
        return self.name


class CourseBooking(models.Model):
    course = models.ForeignKey(Course)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    persons = models.IntegerField(default=0)
    booking_date = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)

    class Meta:
        db_table = 'course_booking'
        verbose_name_plural = 'CourseBooking'

    def __unicode__(self):
        return self.name


class CourseRegister(models.Model):
    course_open = models.ForeignKey(CourseOpen)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    persons = models.IntegerField(default=0)
    reg_date = models.DateTimeField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    paid_date = models.DateTimeField(null=True, blank=True)
    paid_via = models.CharField(max_length=50, null=True, blank=True)
    completed = models.BooleanField(default=False)

    class Meta:
        db_table = 'course_register'
        verbose_name_plural = 'CourseRegister'

    def __unicode__(self):
        return self.name


class Quotation(models.Model):
    course = models.ForeignKey(Course)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    company = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    persons = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

    class Meta:
        db_table = 'quotation'
        verbose_name_plural = 'Quotation'

    def __unicode__(self):
        return self.name

course/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import CourseBooking, CourseRegister, Quotation


class CourseBookingForm(forms.ModelForm):
    persons = forms.ChoiceField(choices=[(x, x) for x in range(1, 20)])

    class Meta:
        model = CourseBooking
        exclude = ['course', 'completed']

    def __init__(self, *args, **kwargs):
        super(CourseBookingForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {
            'required': u'กรุณากรอกชื่อ-นามสกุล',
        }
        self.fields['phone'].error_messages = {
            'required': u'กรุณากรอกเบอร์โทรศัพท์',
        }
        self.fields['email'].error_messages = {
            'required': u'กรุณากรอกอีเมล์',
            'invalid': u'รูปแบบของอีเมล์ไม่ถูกต้อง',
        }
        self.fields['persons'].error_messages = {
            'required': u'กรุณาระบุจำนวนผู้เข้าอบรม',
        }


class QuotationForm(forms.ModelForm):
    persons = forms.ChoiceField(choices=[(x, x) for x in range(1, 20)])

    class Meta:
        model = Quotation
        exclude = ['course', 'completed']

    def __init__(self, *args, **kwargs):
        super(QuotationForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {
            'required': u'กรุณากรอกชื่อ-นามสกุล',
        }
        self.fields['phone'].error_messages = {
            'required': u'กรุณากรอกเบอร์โทรศัพท์',
        }
        self.fields['email'].error_messages = {
            'required': u'กรุณากรอกอีเมล์',
            'invalid': u'รูปแบบของอีเมล์ไม่ถูกต้อง',
        }
        self.fields['company'].error_messages = {
            'required': u'กรุณากรอกชื่อหน่วยงาน',
        }


class CourseRegisterForm(forms.ModelForm):
    persons = forms.ChoiceField(choices=[(x, x) for x in range(1, 20)])

    class Meta:
        model = CourseRegister
        exclude = ['course_open', 'paid', 'completed']

    def __init__(self, *args, **kwargs):
        super(CourseRegisterForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {
            'required': u'กรุณากรอกชื่อ-นามสกุล',
        }
        self.fields['phone'].error_messages = {
            'required': u'กรุณากรอกเบอร์โทรศัพท์',
        }
        self.fields['email'].error_messages = {
            'required': u'กรุณากรอกอีเมล์',
            'invalid': u'รูปแบบของอีเมล์ไม่ถูกต้อง',
        }
        self.fields['persons'].error_messages = {
            'required': u'กรุณาระบุจำนวนผู้เข้าอบรม',
        }

course/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.core.mail import EmailMultiAlternatives, EmailMessage

from taggit.models import Tag
from app.models import Account, Category

from .models import (
    Course,
    CourseOpen,
    CourseBooking,
    CourseRegister,
    Quotation,
)

from .forms import (
    CourseBookingForm,
    CourseRegisterForm,
    QuotationForm,
)


def index(request):
    categories = Category.objects.all()
    courses = Course.objects.all().order_by('code')

    # filter by category
    if request.GET.get('id'):
        courses = courses.filter(category=request.GET.get('id'))

    # filter by tags
    tag = None
    tagid = None
    if request.GET.get('tagid'):
        tagid = int(request.GET.get('tagid'))
        tag = get_object_or_404(Tag, id=tagid)
        courses = courses.filter(tags=tagid)

    return render(request, 'course/index.html', {
        'menu': 'course',
        'categories': categories,
        'courses': courses,
        'tag': tag,
    })


def detail(request, slug):
    course = get_object_or_404(Course, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    # get related courses
    ids = course.tags.values_list('id', flat=True)
    related_courses = Course.objects.filter(tags__in=ids).distinct().exclude(id=course.id)[:5]

    return render(request, 'course/detail.html', {
        'menu': 'course',
        'course': course,
        'related_courses': related_courses,
        'accounts': accounts,
    })


def booking(request, slug):
    course = get_object_or_404(Course, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    if request.method == 'POST':
        form = CourseBookingForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            # save booking
            booking = form.save(commit=False)
            booking.course_id = request.POST.get('id')
            booking.save()

            # send by email
            banks = ''
            for b in accounts:
                banks += u"""%s บัญชี <strong>%s</strong> %s %s %s<br>""" % (b.bank, b.acc_code, b.acc_type, b.branch, b.acc_name)

            subject, from_email, to = '[APPCODE] สมัครเรียนหลักสูตรเรียบร้อยแล้ว', 'appcodetraining@gmail.com', form.cleaned_data['email']
            text_content = u'คุณได้สมัครเรียนหลักสูตร %s เรียบร้อยแล้ว' % course.name
            html_content = u'เรียนคุณ %s<br><br>คุณได้สมัครเรียนหลักสูตร <strong>[%s] %s</strong> เรียบร้อยแล้ว<br>คุณสามารถชำระเงินค่าอบรมล่วงหน้าได้ โดยโอนผ่านธนาคารบัญชีใดบัญชีหนึ่งดังนี้<br><br><br>%s<br><br><br><br>ขอบคุณครับ<br>AppCode Team' % (form.cleaned_data['name'], course.code, course.name, banks)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            return HttpResponseRedirect(reverse('course:complete', kwargs={'slug': course.slug}) + '?name=booking')
    else:
        form = CourseBookingForm(initial={'booking_date': datetime.now()}, use_required_attribute=False)
    return render(request, 'course/booking.html', {
        'menu': 'course',
        'form': form,
        'course': course,
    })


def quotation(request, slug):
    course = get_object_or_404(Course, slug=slug)
    if request.method == 'POST':
        form = QuotationForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            # save quotation
            quotation = form.save(commit=False)
            quotation.course_id = request.POST.get('id')
            quotation.save()

            # send by email
            subject, from_email, to = '[APPCODE] ได้รับคำขอใบเสนอราคาแล้ว', 'appcodetraining@gmail.com', form.cleaned_data['email']
            text_content = u'ระบบได้รับคำขอใบเสนอราคาสำหรับหลักสูตร %s เป็นที่เรียบร้อยแล้ว' % course.name
            html_content = u'เรียนคุณ %s<br><br>ระบบได้รับคำขอใบเสนอราคาสำหรับหลักสูตร<strong>[%s] %s</strong> เป็นที่เรียบร้อย<br>ทางบริษัทฯจะดำเนินการจัดส่งใบเสนอราคาให้ท่านต่อไป<br><br><br><br>ขอบคุณครับ<br>AppCode Team' % (form.cleaned_data['name'], course.code, course.name)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            return HttpResponseRedirect(reverse('course:complete', kwargs={'slug': course.slug}) + '?name=quotation')
    else:
        form = QuotationForm(initial={'training_date': datetime.now()}, use_required_attribute=False)
    return render(request, 'course/quotation.html', {
        'menu': 'course',
        'course': course,
        'form': form,
    })


def register(request, slug, open_id):
    course = get_object_or_404(Course, slug=slug)
    course_open = get_object_or_404(CourseOpen, id=open_id)
    accounts = Account.objects.all().order_by('bank')

    if request.method == 'POST':
        form = CourseRegisterForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            # save register
            register = form.save(commit=False)
            register.course_open_id = request.POST.get('id')
            register.reg_date = datetime.now()
            register.save()

            # send by email
            banks = ""
            for b in accounts:
                banks += u"""%s บัญชี <strong>%s</strong> %s %s %s<br>""" % (b.bank, b.acc_code, b.acc_type, b.branch, b.acc_name)

            subject, from_email, to = '[APPCODE] ลงทะเบียนเรียบร้อยแล้ว', 'addcodetraining@gmail.com', form.cleaned_data['email']
            text_content = u'คุณได้ลงทะเบียนหลักสูตร %s เรียบร้อยแล้ว' % course.name
            html_content = u'เรียนคุณ %s<br><br>คุณได้ลงทะเบียนในหลักสูตร <strong>[%s] %s</strong> เป็นที่เรียบร้อยแล้ว<br>กรุณาชำระเงินโดยโอนผ่านธนาคารบัญชีใดบัญชีหนึ่งดังนี้<br><br><br>%s<br>หลังจากโอนแล้วกรุณาแจ้งหลักฐานการชำระเงินมาที่อีเมล appcodetraining@gmail.com หรือ LINE: appcodetraining<br><br>ขอบคุณครับ<br>AppCode Team' % (form.cleaned_data['name'], course.code, course.name, banks)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            return HttpResponseRedirect(reverse('course:complete', kwargs={'slug': course.slug}) + '?name=register')
    else:
        form = CourseRegisterForm(initial={'register_date': datetime.now()}, use_required_attribute=False)
    return render(request, 'course/register.html', {
        'menu': 'course',
        'course': course,
        'course_open': course_open,
        'form': form,
    })


def complete(request, slug):
    course = get_object_or_404(Course, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    return render(request, 'course/complete.html', {
        'menu': 'course',
        'course': course,
        'accouts': accounts,
    })

templates/course/detail.html
{% extends "master/base.html" %}
{% load humanize %}

{% block title %}คอร์สอบรม | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block meta %}
<meta name="description" content="แอพโค้ด เทคโนโลยี, คอร์สอบรม, หลักสูตรอบรม, หลักสูตร{{ course.category.name }}, {{ course.name }}, {{ course.title|truncatewords:10 }}">
<meta name="author" content="AppCode Technology Ltd., {{ course.teacher.name }}">
<meta name="keywords" content="คอร์สอบรม, หลักสูตรอบรม, สอนเขียนโปรแกรม, อบรม, เรียนเขียนโปรแกรม, อบรมโปรแกรม, สอนคอมพิวเตอร์, {{ course.tags.all|join:', ' }}">
<meta property="fb:app_id" content="520613538309239"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ course.name }}" />
<meta property="og:description" content="{{ course.title }}" />
<meta property="og:url" content="http://{{ request.get_host }}{{ request.get_full_path }}" />
{% if course.image %}
<meta property="og:image" content="http://{{ request.get_host }}{{ course.image.url }}" />
{% endif %}
{% endblock %}

{% block content %}
<div id="subnav" class="subnav-course">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'course:index' %}?id={{ request.GET.id }}">คอร์สอบรม</a></li>
        <li class="active">{{ course.code }}</li>
      </ul>
      <h1>รายละเอียด</h1>
    </div>
  </div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="course">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1 style="margin-bottom:20px">{{ course.name }}<br><div class="fb-like" data-href="http://{{ request.get_host }}{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></h1>
        {% if course.title %}
          <span><i class="fa fa-quote-left"></i> {{ course.title }}</span>
        {% endif %}
        <!-- ./ course title -->
        {% if course.outline %}
        <div style="margin:20px 0 40px 0">
          <a href="{{ course.outline.url }}" class="btn btn-info" target="_blank"><i class="fa fa-file-pdf-o"></i> ดาวน์โหลดเป็น PDF</a>
        </div>
        {% endif %}
        <!-- ./ course outline -->
      </div>
      <div class="col-md-4">
        {% if course.courseslider_set.count %}
        <div id="img-slider" style="margin-top:60px">
          <div id="carousel-generic" class="carousel slide carousel-fade" data-ride="carousel" data-interval="10000">
            <ol class="carousel-indicators">
              {% for c in course.courseslider_set.all|dictsort:"name" %}
              <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
              {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
              {% for c in course.courseslider_set.all|dictsort:"name" %}
              <div class="item {% if forloop.first %}active{% endif %} slide{{ forloop.counter }}">
                <img src="{{ c.image.url }}" alt="{{ c.name }}" height="400px">
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        {% else %}
          {% if course.image %}
          <div class="image">
            <img src="{{ course.image.url }}" alt="{{ course.name }}" class="img-responsive">
          </div>
          {% endif %}
        {% endif %}
        <!-- ./ course sliders image -->
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        {% if course.content %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>รายละเอียดหลักสูตร</strong>
            </div>
          </div>
          <div class="panel-body">
            {{ course.content|safe }}
          </div>
        </div>
        {% endif %}
        <!-- ./ course content -->
        {% if accounts|length %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>การชำระเงิน</strong>
            </div>
          </div>
          <div class="panel-body">
            <ul class="bank-list">
              {% for b in accounts %}
              <li>
                {% if b.image %}<img src="{{ b.image.url }}" alt="{{ b.bank }}">{% endif %}
                <span>{{ b.bank }} สาขา{{ b.branch }} บัญชี <strong>{{ b.acc_code }}</strong> {{ b.type }} {{ b.acc_name }}</span>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
        <!-- ./ course payment accounts -->
      </div>
      <div class="col-md-4">
        {% if course.promotion %}
        <div class="well" style="text-align:center">
          <strong style="color:#0000ff">{{ course.promotion }}</strong>
        </div>
        {% endif %}
        <!-- ./ course promotion -->
        <div class="pricing">
          <h3>ราคา <span>{{ course.price|floatformat:0|intcomma }}</span> บาท</h3>
          <div style="margin-bottom:30px">( ราคานี้ยังไม่รวมภาษีมูลค่าเพิ่ม )</div>
        </div>
        <!-- ./ course pricing -->
        {% if course.get_course_opens.count %}
          <div class="form-group">
            <h3>ลงทะเบียน</h3>
            {% for o in course.get_course_opens %}
              <a href="{% url 'course:register' slug=course.slug open_id=o.id %}?round={{ forloop.counter }}" class="btn btn-primary btn-lg btn-block"><i class="fa fa-calendar"></i> รอบที่ {{ forloop.counter }} : {{ o.times }}</a>
            {% endfor %}
          </div>
        {% else %}
          <a href="{% url 'course:booking' slug=course.slug %}?id={{ request.GET.id }}" class="btn btn-primary btn-lg btn-block">สมัครเรียนคอร์สนี้</a>
          <a href="{% url 'course:quotation' slug=course.slug %}?id={{ request.GET.id }}" class="btn btn-warning btn-lg btn-block"><i class="fa fa-copy"></i> ขอใบเสนอราคา</a>
        {% endif %}
        <!-- ./ course booking / registration or quotations -->
        {% if course.courseoption_set.count %}
        <div class="form-group">
          <h3>สิ่งที่เราเตรียมให้</h3>
          <ul class="check-list">
            {% for o in course.courseoption_set.all %}
            <li><i class="fa fa-check"></i> {{ o.option }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ course options -->
        {% if course.teachers.count %}
        <div class="form-group">
          <h3>อาจารย์ผู้สอน</h3>
          {% for t in course.teachers.all %}
          <div class="profile">
            <img src="{{ t.image.url }}" alt="{{ t.name }}">
            <div class="profile-item">
              <h4>{{ t.fullname }}</h4>
              <div class="caption">{{ t.position }}</div>
              <a style="cursor:pointer" data-toggle="collapse" data-target="#demo{{forloop.counter}}">ดูโปรไฟล์แบบเต็ม</a>
              <div id="demo{{forloop.counter}}" class="collapse">
                {{ t.profile|default_if_none:''|safe }}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <!-- ./ course teacher -->
        {% if related_courses|length %}
        <div class="form-group">
          <h3>คอร์สที่เกี่ยวข้อง</h3>
          <ul class="course-link">
            {% for r in related_courses %}
            <li>
              <a href="{% url 'course:detail' slug=r.slug %}">
                <img src="{{ r.image.url }}" alt="{{ r.name }}">
                <div class="item">
                  <strong>{{ r.name }}</strong>
                  <div class="subtext">
                    <span>ระยะเวลา {{ r.hours }} ชั่วโมง ({{ r.days }} วัน) / <strong>{{ r.price|floatformat:0|intcomma }} ฿</strong></span>
                  </div>
                </div>
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ course related -->
        {% if course.tags.count %}
        <div class="form-group">
          <h3>ป้ายกำกับ</h3>
          <ul class="tags">
            {% for t in course.tags.all %}
            <li><a href="{% url 'course:index' %}?tagid={{ t.id }}">{{ t.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ course tags list -->
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/course/finish.html
{% extends "master/base.html" %}