app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^jobs/$', views.jobs, name='jobs'),
    url(r'^login/$', views.login, name='login'),
]

appcode/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse

from . import views

urlpatterns = [
    url(r'^home/',views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^', include('app.urls', namespace='app')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^robots.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = 'AppCode'
admin.site.site_header = 'AppCode Technology'

online/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/checkout$', views.checkout, name='checkout'),
    url(r'^(?P<slug>[\w-]+)/finish$', views.finish, name='finish'),
]

online/models.py
from django.db import models
from taggit.managers import TaggableManager

from app.models import Account, Category, Teacher, Member


class Video(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=150, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    teachers = models.ManyToManyField(Teacher, blank=True)
    lessons = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    image = models.FileField(upload_to='images/video', null=True, blank=True)
    premium = models.BooleanField(default=False)
    published = models.BooleanField(default=True)
    tags = TaggableManager()

    class Meta:
        db_table = 'video'
        verbose_name_plural = 'Video'

    def __unicode__(self):
        return self.name


class VideoOption(models.Model):
    video = models.ForeignKey(Video)
    option = models.CharField(max_length=50)

    class Meta:
        db_table = 'video_option'
        verbose_name_plural = 'VideoOption'

    def __unicode__(self):
        return self.option


class VideoPlaylist(models.Model):
    video = models.ForeignKey(Video)
    no = models.IntegerField()
    chapter = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    time = models.CharField(max_length=20, null=True, blank=True)
    preview = models.BooleanField(default=False)
    link = models.URLField(max_length=200, null=True, blank=True)

    class Meta:
        db_table = 'video_playlist'
        verbose_name_plural = 'VideoPlaylist'

    def __unicode__(self):
        return self.title


class VideoRegister(models.Model):
    video = models.ForeignKey(Video)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100)
    unit = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    reg_date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    paid_date = models.DateTimeField(null=True, blank=True)
    paid_via = models.CharField(max_length=50, null=True, blank=True)
    authorized = models.BooleanField(default=False)
    authorized_token = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        db_table = 'video_register'
        verbose_name_plural = 'VideoRegister'

    def __unicode__(self):
        return self.name

online/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import VideoRegister


class VideoRegisterForm(forms.ModelForm):
    class Meta:
        model = VideoRegister
        exclude = ['video', 'paid', 'paid_date', 'paid_via', 'authorized']

    def __init__(self, *args, **kwargs):
        super(VideoRegisterForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {
            'required': u'กรุณากรอกชื่อของท่าน',
        }
        self.fields['email'].error_messages = {
            'required': u'กรุณากรอกอีเมล์',
            'invalid': u'รูปแบบของอีเมล์ไม่ถูกต้อง',
        }

online/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import EmailMultiAlternatives, EmailMessage

from taggit.models import Tag
from app.models import Account
from .models import Video, VideoRegister
from .forms import VideoRegisterForm
import jwt

TOKEN_SECRET = '-vg-hkwxsojvp'

def index(request):
    videos = Video.objects.filter(published=True).order_by('-premium')

    # filter by tags
    tag = None
    tagid = None
    if request.GET.get('tagid'):
        tagid = int(request.GET.get('tagid'))
        tag = get_object_or_404(Tag, id=tagid)
        videos = videos.filter(tags=tagid)

    return render(request, 'online/index.html', {
        'menu': 'online',
        'videos': videos,
        'tag': tag,
    })


def detail(request, slug):
    video = get_object_or_404(Video, slug=slug)

    # get related videos
    ids = video.tags.values_list('id', flat=True)
    related_videos = Video.objects.filter(tags__in=ids).distinct().exclude(id=video.id)[:5]

    # check video auto playing
    autoplay = False
    player= None
    pl = request.GET.get('pl')
    active_pl = -1
    if pl:
        autoplay = True
        player = video.videoplaylist_set.filter(id=int(pl)).first()
    else:
        player = video.videoplaylist_set.first()
        if player:
            active_pl = player.id

    # check video authenticated
    is_locked = False
    if video.price:
        is_locked = True

    # video token authentications
    token = None
    if request.user.is_authenticated():
        register = VideoRegister.objects.filter(email=request.user.email, video_id=video.id).first()
        if register and register.authorized:
            is_locked = False
        token = jwt.encode({'user_id': request.user.id, 'is_lock': is_locked, 'is_preview': player.preview}, TOKEN_SECRET, algorithm='HS256')
    else:
        token = jwt.encode({'is_lock': is_locked, 'is_preview': player.preview}, TOKEN_SECRET, algorithm='HS256')

    return render(request, 'online/detail.html', {
        'menu': 'online',
        'video': video,
        'related_videos': related_videos,
        'player': player,
        'autoplay': autoplay,
        'active_pl': active_pl,
        'is_locked': is_locked,
        'token': token,
    })


def checkout(request, slug):
    video = get_object_or_404(Video, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    if request.method == 'POST':
        form = VideoRegisterForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            # save video register
            register = form.save(commit=False)
            register.video_id = request.POST.get('id')
            register.save()

            # send by email
            banks = ''
            for b in accounts:
                banks += u"""%s บัญชี <strong>%s</strong> %s %s %s<br>""" % (b.bank, b.acc_code, b.acc_type, b.branch, b.acc_name)

            subject, from_email, to = '[APPCODE] สั่งซื้อคอร์สออนไลน์', 'appcodetraining@gmail.com', form.cleaned_data['email']
            text_content = u'คุณได้สั่งซื้อหนังสือ %s เรียบร้อยแล้ว' % video.name
            html_content = u'เรียนคุณ %s<br><br>คุณได้สั่งซื้อคอร์สออนไลน์ <strong>[%s] %s</strong> เรียบร้อยแล้ว<br>กรุณาโอนเงินจำนวน <strong>%s</strong> บาท โดยโอนผ่านธนาคารบัญชีใดบัญชีหนึ่งดังนี้<br><br><br>%s<br><br>หลังจากโอนแล้วกรุณาแจ้งหลักฐานการชำระเงินมาที่อีเมล appcodetraining@gmail.com หรือ LINE: appcodetraining<br><br>ขอบคุณครับ<br>AppCode Team' % (form.cleaned_data['name'], video.code, video.name, register.amount, banks)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            messages.success(request, u'สั่งซื้อคอร์สออนไลน์เรียบร้อยแล้ว โปรดตรวจสอบรายละเอียดได้ทางอีเมลของท่าน!')
            return HttpResponseRedirect(reverse('online:finish', kwargs={'slug': video.slug}) + '?regid=' + str(register.id))
    else:
        form = VideoRegisterForm(use_required_attribute=False)
    return render(request, 'online/checkout.html', {
        'menu': 'online',
        'video': video,
        'form': form,
    })


def finish(request, slug):
    regid = request.GET.get('regid')
    video = get_object_or_404(Video, slug=slug)
    register = VideoRegister.objects.get(pk=regid)
    accounts = Account.objects.all().order_by('bank')

    return render(request, 'online/finish.html', {
        'menu': 'online',
        'video': video,
        'register': register,
        'accounts': accounts,
    })

templates/online/checkout.html
{% extends "master/base.html" %}
{% load humanize widget_tweaks %}

{% block title %}คอร์สออนไลน์ | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block meta %}
<meta name="description" content="แอพโค้ด เทคโนโลยี, หนังสือ, คู่มือ, E-Book, คอร์สออนไลน์ {{ video.category.name }}, {{ video.name }}, {{ video.title }}">
<meta name="author" content="AppCode Technology Ltd., {{ book.teacher.name }}">
<meta name="keywords" content="หนังสือ, หนังสือเขียนโปรแกรม, คู่มือเขียนโปรแกรม, หนังสือคอมพิวเตอร์, E-Book, คอร์สออนไลน์, {{ video.tags.all|join:', ' }}">
<meta property="fb:app_id" content="520613538309239"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ video.name }}" />
<meta property="og:description" content="{{ video.title }}" />
<meta property="og:url" content="http://{{ request.get_host }}{{ request.get_full_path }}" />
{% if book.image %}
<meta property="og:image" content="http://{{ request.get_host }}{{ video.image.url }}" />
{% endif %}
{% endblock %}

{% block content %}
<div id="subnav" class="subnav-online">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'online:index' %}">คอร์สออนไลน์</a></li>
        <li><a href="{% url 'online:detail' slug=video.slug %}">{{ video.code }}</a></li>
        <li class="active">การสั่งซื้อ</li>
      </ul>
      <h1>สั่งซื้อคอร์สออนไลน์</h1>
    </div>
  </div>
</div>
<div class="block">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>ตะกร้าสินค้า</h1>
        <table class="table table-bordered table-cart">
          <thead>
            <tr>
              <th width="15%">รหัสสินค้า</th>
              <th>ชื่อสินค้า</th>
              <th>จำนวน</th>
              <th style="text-align:right" width="18%">ราคา/หน่วย</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ video.code }}</td>
              <td>คอร์สออนไลน์: {{ video.name }} ({{ video.lessons }} บทเรียน)</td>
              <td align="right">1</td>
              <td align="right" style="font-family:'Open Sans'">{{ video.price|floatformat:0|intcomma }}</td>
            </tr>
          </tbody>
        </table>
        <h3>รวมเป็นเงินทั้งสิ้น <span id="totallabel" style="color:#c30">2500.00</span> บาท</h3>
      </div>
      <div class="col-md-5">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>ข้อมูลการสั่งซื้อ</strong>
            </div>
          </div>
          <div class="panel-body">
            <form action="{% url 'online:checkout' slug=video.slug %}" method="post" id="checkoutform">
              {% csrf_token %}
              <input type="hidden" id="id" name="id" value="{{ video.id }}">
              <input type="hidden" id="type" name="type" value="{{ request.GET.type }}">
              <input type="hidden" id="price" name="price" value="{{ video.price }}">
              <input type="hidden" id="amount" name="amount">
              <input type="hidden" id="unit" name="unit">
              <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                <label>ชื่อ <span class="asteriskField">*</span></label>
                {% render_field form.name class="form-control" placeholder="ชื่อของท่าน" value=user.username %}
                <span class="help-block">
                  {% for error in form.name.errors %}{{ error }}{% endfor %}
                </span>
              </div>
              <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                <label>อีเมล <span class="asteriskField">*</span></label>
                {% render_field form.email class="form-control" placeholder="กรอกอีเมล" value=user.email %}
                <span class="help-block">
                  {% for error in form.email.errors %}{{ error }}{% endfor %}
                </span>
              </div>
              <div class="form-group">
                <label>เบอร์โทรศัพท์</label>
                {% render_field form.phone class="form-control" placeholder="เบอร์ติดต่อ" %}
              </div>
            </form>
          </div>
          <div class="panel-footer" style="overflow:hidden">
            <div class="pull-left">
              <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" id="paypalform">
                <input type="hidden" name="cmd" value="_xclick">
                <input TYPE="hidden" name="charset" value="utf-8">
                <input type="hidden" name="hosted_button_id" value="PM5MMZ7JL9EZC">
                <input type="hidden" name="business" value="appcodetraining@gmail.com">
                <input type="hidden" name="currency_code" value="THB">
                <input type="hidden" name="item_name" value="{{ video.name }}">
                <input type="hidden" id="_qty" name="quantity" value="0">
                <input type="hidden" id="_amount" name="amount" value="0">
                <input type="image" src="https://www.paypalobjects.com/th_TH/TH/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - วิธีชำระเงินแบบออนไลน์ที่ปลอดภัยกว่าและง่ายกว่า!">
              </form>
            </div>
            <a href="#" class="btn btn-success btn-lg pull-right" id="btnregister"><i class="fa fa-check"></i> สั่งซื้อคอร์สนี้</a>
          </div>
        </div>
        <a href="{% url 'online:detail' slug=video.slug %}" style="text-decoration:none"><i class="fa fa-chevron-left"></i> กลับหน้าที่แล้ว</a>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  function calPrice() {
    var qty = 1;
    var price = parseFloat($('#price').val() || '0');
    return qty * price;
  }

  function formatNumber(v) {
    return v.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
  }

  function displayPrice() {
    var total = calPrice();
    $('#amount').val(total);
    $('#totallabel').html(formatNumber(total + ''));
  }

  $(function () {
    $('input[name="name"]').focus();
    displayPrice();

    $('#paypalform').on('submit', function () {
      $('#_qty').val(1);
      $('#_amount').val($('#price').val());
    });

    $('#btnregister').on('click', function () {
      $('#unit').val(1);
      $('#checkoutform').submit();
    });
  });
</script>
{% endblock %}

templates/online/detail.html
{% extends "master/base.html" %}
{% load humanize %}

{% block title %}คอร์สออนไลน์ | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block meta %}
<meta name="description" content="แอพโค้ด เทคโนโลยี, หนังสือ, คู่มือ, E-Book, คอร์สออนไลน์ {{ video.category.name }}, {{ video.name }}, {{ video.title }}">
<meta name="author" content="AppCode Technology Ltd., {{ book.teacher.name }}">
<meta name="keywords" content="หนังสือ, หนังสือเขียนโปรแกรม, คู่มือเขียนโปรแกรม, หนังสือคอมพิวเตอร์, E-Book, คอร์สออนไลน์, {{ video.tags.all|join:', ' }}">
<meta property="fb:app_id" content="520613538309239"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ video.name }}" />
<meta property="og:description" content="{{ video.title }}" />
<meta property="og:url" content="http://{{ request.get_host }}{{ request.get_full_path }}" />
{% if book.image %}
<meta property="og:image" content="http://{{ request.get_host }}{{ video.image.url }}" />
{% endif %}
{% endblock %}

{% block script %}
<link type="text/css" rel="stylesheet" href="/static/vendor/flowplayer/skin/skin.css">
<script type="text/javascript" src="/static/vendor/flowplayer/flowplayer.min.js"></script>
<script type="text/javascript" src="/static/vendor/flowplayer/flowplayer.hlsjs.light.min.js"></script>
{% endblock %}

{% block content %}
<div id="subnav" class="subnav-online">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'online:index' %}">คอร์สออนไลน์</a></li>
        <li class="active">{{ video.code }}</li>
      </ul>
      <h1>บทเรียนออนไลน์</h1>
    </div>
  </div>
</div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="course">
  <div class="container">
    <h1 style="margin-bottom:20px">{{ video.name }}<br><div class="fb-like" data-href="http://{{ request.get_host }}{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></h1>
    <div class="row">
      <div class="col-md-8">
        {% if player %}
          <div class="flowplayer" id="player"></div>
        {% elif video.image %}
          <img src="{{ video.image.url }}" style="width:80%">
        {% endif %}
        <!-- ./player screen -->
        {% if player %}
        <h3>จำนวน {{ video.lessons }} บทเรียน</h3>
        <div class="panel panel-default">
          <table class="table table-playlist">
          {% regroup video.videoplaylist_set.all|dictsort:"no" by chapter as playlists %}
          {% for pl in playlists %}
            <thead>
              <tr><th colspan="5">{{ pl.grouper }}</th></tr>
            </thead>
            <tbody>
              {% for c in pl.list|dictsort:"no" %}
              <tr class="{% if request.GET.pl|add:0 == c.id or active_pl == c.id %}active{% endif %}">
                <td>{{ c.title }}</td>
                <td>{% if c.preview %}<span class="label label-info">ตัวอย่าง</span>{% endif %}</td>
                <td>
                  {% if is_locked and c.preview == False %}
                    <i class="fa fa-lock" style="color:#999"></i>
                  {% else %}
                    {% if request.GET.pl|add:0 == c.id or active_pl == c.id %}
                    <span class="label label-default">กำลังเล่น</span>
                    {% else %}
                    <a href="{% url 'online:detail' slug=video.slug %}?pl={{c.id}}"><i class="fa fa-play-circle-o"></i></a>
                    {% endif %}
                  {% endif %}
                </td>
                <td><i class="fa fa-clock-o"></i> {{ c.time }}</td>
              </tr>
              {% endfor %}
            </tbody>
          {% endfor %}
          </table>
        </div>
        {% endif %}
        <!-- ./player playlist -->
      </div>
      <div class="col-md-4">
        {% if video.price > 0 %}
        <div class="pricing">
          <h3>ราคา <span>{{ video.price|floatformat:0|intcomma }}</span> บาท</h3>
        </div>
        <a href="{% url 'online:checkout' slug=video.slug %}" class="btn btn-success btn-lg btn-block">สั่งซื้อคอร์สนี้</a>
        <div class="remark">( ดูซ้ำกี่ครั้งก็ได้ แบบไม่จำกัด )</div>
        {% endif %}
        <!-- ./price & ordering -->
        {% if video.description %}
        <div class="form-group">
          <h3>คำอธิบาย</h3>
        </div>
        <span><i class="fa fa-quote-left"></i> {{ video.description }}</span>
        {% endif %}
        <!-- ./video description -->
        {% if video.videooption_set.count %}
        <div class="form-group">
          <h3>สิ่งที่มีมาด้วย</h3>
        </div>
        <ul class="check-list">
          {% for o in video.videooption_set.all %}
          <li><i class="fa fa-check"></i> {{ o.option }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        <!-- ./ video check lists -->
        {% if video.teachers.count %}
        <div class="form-group">
          <h3>ผู้สอน</h3>
          {% for t in video.teachers.all %}
          <div class="profile">
            <img src="{{ t.image.url }}" alt="{{ t.name }}">
            <div class="profile-item">
              <h4>{{ t.fullname }}</h4>
              <div class="caption">{{ t.position }}</div>
              <a style="cursor:pointer" data-toggle="collapse" data-target="#demo{{forloop.counter}}">ดูโปรไฟล์แบบเต็ม</a>
              <div id="demo{{forloop.counter}}" class="collapse">
                {{ t.profile|default_if_none:''|safe }}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <!-- ./ video teacher -->
        {% if related_videos|length %}
        <div class="form-group">
          <h3>คอร์สที่เกี่ยวข้อง</h3>
          <ul class="course-link">
            {% for r in related_videos %}
            <li>
              <a href="{% url 'online:detail' slug=r.slug %}">
                <img src="{{ r.image.url }}" alt="{{ r.name }}">
                <div class="item">
                  <strong>{{ r.name }}</strong>
                  <div class="subtext">
                    <span>จำนวน {{ r.lessons }} บทเรียน / <strong>{{ r.price|floatformat:0|intcomma }} ฿</strong></span>
                  </div>
                </div>
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ video related links -->
        {% if video.tags.count %}
        <div class="form-group">
          <h3>ป้ายกำกับ</h3>
          <ul class="tags">
            {% for t in video.tags.all %}
            <li><a href="{% url 'online:index' %}?tagid={{ t.id }}">{{ t.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ course tags list -->
      </div>
    </div>
  </div>
</div>
{% if player %}
  <script type="text/javascript">
    function playVideo() {
      var auto = '{{ autoplay }}';
      var player = flowplayer("#player", {
        autoplay: auto === 'True',
        splash: auto === 'True' ? false : '{{ video.image.url }}',
        clip: {
          sources: [{
              type: 'video/mp4',
              src: '{{ player.link }}?token={{ token }}',
          }],
          title: '{{ player.title }}'
        },
      });
      player.volumeLevel = 0.5;
    }

    window.onload = function () {
      var link = '{{ player.link }}';
      if(link != 'None') {
        playVideo();
      } else {
        alert('ลิงค์มีปัญหา! ไม่สามารถเล่นวีดีโอได้');
      }
    };
  </script>
{% endif %}
{% endblock %}

templates/online/index.html
{% extends "master/base.html" %}
{% load humanize %}

{% block title %}คอร์สออนไลน์ | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block content %}
<div id="subnav" class="subnav-online">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li class="active">คอร์สออนไลน์</li>
      </ul>
      <h1>คอร์สออนไลน์</h1>
    </div>
  </div>
</div>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="lead">เรียนได้ทันที ทุกที่ ทุกเวลา สามารถเรียนซ้ำได้แบบไม่จำกัด มีให้เลือกทั้งคอร์สพรีเมี่ยม และคอร์สที่เรียนได้ฟรี</div>
      </div>
    </div>
    {% if tag %}
      <h3>Tag : {{ tag.name }}</h3>
    {% endif %}
    {% for v in videos %}
      {% if forloop.first %}<div class="row">{% endif %}
      <div class="col-md-3">
        <div class="online">
          <div class="image">
            {% if v.premium %}
              <span class="label label-warning">แนะนำ</span>
            {% endif %}
            {% if v.image %}
              <img src="{{ v.image.url }}" alt="{{ v.name }}">
            {% endif %}
          </div>
          <div class="content">
            <h4><a href="{% url 'online:detail' slug=v.slug %}">{{ v.name }}</a></h4>
            <div class="preview">{{ v.title }}</div>
            <span><i class="fa fa-book"></i> {{ v.lessons }} บทเรียน</span>
            <div class="footer">
              <a href="{% url 'online:detail' slug=v.slug %}" class="btn btn-success pull-left">เข้าสู่บทเรียน</a>
              <span class="pricing {% if v.price > 0 %}price-green{% else%}price-red{% endif %}">
                {% if v.price > 0 %}{{ v.price|floatformat:0|intcomma }} ฿{% else %}เรียนฟรี{% endif %}
              </span>
            </div>
          </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
      {% if forloop.last %}</div>{% endif %}
    {% endfor %}
  </div>
</section>
{% endblock %}