app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^jobs/$', views.jobs, name='jobs'),
    url(r'^login/$', views.login, name='login'),
]

appcode/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse

from . import views

urlpatterns = [
    url(r'^home/',views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^', include('app.urls', namespace='app')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^robots.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = 'AppCode'
admin.site.site_header = 'AppCode Technology'

course/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/booking/$', views.booking, name='booking'),
    url(r'^(?P<slug>[\w-]+)/quotation/$', views.quotation, name='quotation'),
    url(r'^(?P<slug>[\w-]+)/complete/$', views.complete, name='complete'),
    url(r'^(?P<slug>[\w-]+)/(?P<open_id>[\d]+)/register/$', views.register, name='register'),
]

online/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/checkout$', views.checkout, name='checkout'),
    url(r'^(?P<slug>[\w-]+)/finish$', views.finish, name='finish'),
]

book/models.py
from django.db import models
from taggit.managers import TaggableManager

from app.models import Teacher, Category


BOOK_TYPE_CHOICE = (
    ('B', 'Both'),
    ('E', 'e-Book'),
    ('P', 'Paperback'),
)


def get_book_file(instance, filename):
    return 'upload/book/%s/%s' % (instance.code, filename)


def get_book_exam_file(instance, filename):
    return 'upload/book/exam/%s/%s' % (instance.code, filename)


class Book(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    preview = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    teacher = models.ForeignKey(Teacher, null=True, blank=True)
    type = models.CharField(max_length=1, choices=BOOK_TYPE_CHOICE)
    pages = models.IntegerField(default=0)
    years = models.IntegerField(default=0)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    price_ebook = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    example = models.FileField(upload_to=get_book_exam_file, null=True, blank=True)
    image = models.FileField(upload_to=get_book_file, null=True, blank=True)
    published = models.BooleanField(default=True)
    tags = TaggableManager()

    class Meta:
        db_table = 'book'
        verbose_name_plural = 'Book'

    def __unicode__(self):
        return self.name


class BookOption(models.Model):
    book = models.ForeignKey(Book)
    option = models.CharField(max_length=50)

    class Meta:
        db_table = 'book_option'
        verbose_name_plural = 'BookOption'

    def __unicode__(self):
        return self.option


class Register(models.Model):
    book = models.ForeignKey(Book)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100)
    address = models.TextField(null=True, blank=True)
    unit = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    reg_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    paid = models.BooleanField(default=False)
    paid_date = models.DateTimeField(null=True, blank=True)
    paid_via = models.CharField(max_length=50, null=True, blank=True)
    delivered = models.BooleanField(default=False)

    class Meta:
        db_table = 'book_register'
        verbose_name_plural = 'Register'
        ordering = ['reg_date']

    def __unicode__(self):
        return self.book.name

book/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Register


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Register
        exclude = ['book', 'paid', 'paid_date', 'paid_via', 'delivered']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {
            'required': u'กรุณากรอกชื่อของท่าน',
        }
        self.fields['email'].error_messages = {
            'required': u'กรุณากรอกอีเมล์',
            'invalid': u'รูปแบบของอีเมล์ไม่ถูกต้อง',
        }

book/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import EmailMultiAlternatives, EmailMessage

from taggit.models import Tag
from app.models import Account
from .models import Book, Register
from .forms import RegisterForm


def index(request):
    books = Book.objects.filter(published=True).order_by('id')

    # filter by tags
    tag = None
    tagid = None
    if request.GET.get('tagid'):
        tagid = int(request.GET.get('tagid'))
        tag = get_object_or_404(Tag, id=tagid)
        books = books.filter(tags=tagid)

    return render(request, 'book/index.html', {
        'menu': 'book',
        'books': books,
        'tag': tag,
    })


def detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    # get related books
    ids = book.tags.values_list('id', flat=True)
    related_books = Book.objects.filter(tags__in=ids).distinct().exclude(id=book.id)[:5]

    return render(request, 'book/detail.html', {
        'menu': 'book',
        'book': book,
        'related_books': related_books,
        'accounts': accounts,
    })


def checkout(request, slug):
    book = get_object_or_404(Book, slug=slug)
    accounts = Account.objects.all().order_by('bank')

    if request.method == 'POST':
        form = RegisterForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            # save book register
            register = form.save(commit=False)
            register.book_id = request.POST.get('id')
            register.save()

            # send by email
            banks = ''
            for b in accounts:
                banks += u"""%s บัญชี <strong>%s</strong> %s %s %s<br>""" % (b.bank, b.acc_code, b.acc_type, b.branch, b.acc_name)

            subject, from_email, to = '[APPCODE] สั่งซื้อหนังสือ', 'appcodetraining@gmail.com', form.cleaned_data['email']
            text_content = u'คุณได้สั่งซื้อหนังสือ %s เรียบร้อยแล้ว' % book.name
            html_content = u'เรียนคุณ %s<br><br>คุณได้สั่งซื้อหนังสือ <strong>[%s] %s</strong> เรียบร้อยแล้ว<br>กรุณาโอนเงินจำนวน <strong>%s</strong> บาท โดยโอนผ่านธนาคารบัญชีใดบัญชีหนึ่งดังนี้<br><br><br>%s<br><br>หลังจากโอนแล้วกรุณาแจ้งหลักฐานการชำระเงินมาที่อีเมล appcodetraining@gmail.com หรือ LINE: appcodetraining<br><br>ขอบคุณครับ<br>AppCode Team' % (form.cleaned_data['name'], book.code, book.name, register.amount, banks)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            messages.success(request, u'สั่งซื้อหนังสือเรียบร้อยแล้ว โปรดตรวจสอบรายละเอียดได้ทางอีเมลของท่าน!')
            return HttpResponseRedirect(reverse('book:finish', kwargs={'slug': book.slug}) + '?regid=' + str(register.id))
    else:
        form = RegisterForm(use_required_attribute=False)
    return render(request, 'book/checkout.html', {
        'menu': 'book',
        'book': book,
        'form': form,
    })


def finish(request, slug):
    regid = request.GET.get('regid')
    book = get_object_or_404(Book, slug=slug)
    register = Register.objects.get(pk=regid)
    accounts = Account.objects.all().order_by('bank')

    return render(request, 'book/finish.html', {
        'menu': 'book',
        'book': book,
        'register': register,
        'accounts': accounts,
    })

templates/book/checkout.html
{% extends "master/base.html" %}
{% load humanize widget_tweaks %}

{% block title %}หนังสือ | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block meta %}
<meta name="description" content="แอพโค้ด เทคโนโลยี, หนังสือ, คู่มือ, E-Book, หนังสือ{{ book.category.name }}, {{ book.name }}, {{ book.title }}">
<meta name="author" content="AppCode Technology Ltd., {{ book.teacher.name }}">
<meta name="keywords" content="หนังสือ, หนังสือเขียนโปรแกรม, คู่มือเขียนโปรแกรม, หนังสือคอมพิวเตอร์, E-Book, {{ book.tags.all|join:', ' }}">
<meta property="fb:app_id" content="520613538309239"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ book.name }}" />
<meta property="og:description" content="{{ book.title }}" />
<meta property="og:url" content="http://{{ request.get_host }}{{ request.get_full_path }}" />
{% if book.image %}
<meta property="og:image" content="http://{{ request.get_host }}{{ book.image.url }}" />
{% endif %}
{% endblock %}

{% block content %}
<div id="subnav" class="subnav-book">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'book:index' %}">หนังสือ</a></li>
        <li><a href="{% url 'book:detail' slug=book.slug %}">{{ book.code }}</a></li>
        <li class="active">การสั่งซื้อ</li>
      </ul>
      <h1>สั่งซื้อหนังสือ</h1>
    </div>
  </div>
</div>
<div class="block">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>ตะกร้าสินค้า</h1>
        <table class="table table-bordered table-cart">
          <thead>
            <tr>
              <th width="15%">รหัสสินค้า</th>
              <th>ชื่อสินค้า</th>
              <th width="15%">จำนวน</th>
              <th style="text-align:right" width="18%">ราคา/หน่วย</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ book.code }}</td>
              <td>หนังสือ: {{ book.name }} {% if request.GET.type == 'paper' %}(หนังสือเล่ม){% else %}e-Book [PDF]{% endif %}</td>
              <td align="right">
                <select name="qty" id="qty" class="form-control">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                </select>
              </td>
              <td align="right" style="font-family:'Open Sans'">{% if request.GET.type == 'paper' %}<strong>{{ book.price|floatformat:0|intcomma }}</strong>{% else %}<strong>{{ book.price_ebook|floatformat:0|intcomma }}</strong>{% endif %}</td>
            </tr>
          </tbody>
        </table>
        <h3>รวมเป็นเงินทั้งสิ้น <span id="totallabel" style="color:#c30">2500.00</span> บาท</h3>
      </div>
      <div class="col-md-5">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>ข้อมูลการสั่งซื้อ</strong>
            </div>
          </div>
          <div class="panel-body">
            <form action="{% url 'book:checkout' slug=book.slug %}" method="post" id="checkoutform">
              {% csrf_token %}
              <input type="hidden" id="id" name="id" value="{{ book.id }}">
              <input type="hidden" id="type" name="type" value="{{ request.GET.type }}">
              <input type="hidden" id="price" name="price" value="{% if request.GET.type == 'paper' %}{{ book.price }}{% else %}{{ book.price_ebook}}{% endif %}">
              <input type="hidden" id="amount" name="amount">
              <input type="hidden" id="unit" name="unit">
              <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                <label>ชื่อ <span class="asteriskField">*</span></label>
                {% render_field form.name class="form-control" placeholder="ชื่อของท่าน" value=user.username %}
                <span class="help-block">
                  {% for error in form.name.errors %}{{ error }}{% endfor %}
                </span>
              </div>
              <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                <label>อีเมล <span class="asteriskField">*</span></label>
                {% render_field form.email class="form-control" placeholder="กรอกอีเมล" value=user.email %}
                <span class="help-block">
                  {% for error in form.email.errors %}{{ error }}{% endfor %}
                </span>
              </div>
              <div class="form-group">
                <label>เบอร์โทรศัพท์</label>
                {% render_field form.phone class="form-control" placeholder="เบอร์ติดต่อ" %}
              </div>
              <div class="form-group">
                <label>สถานที่จัดส่ง</label>
                {{ form.address|attr:"class:form-control"|attr:"rows:4"|attr:"placeholder:กรอกที่อยู่เพื่อจัดส่งสินค้า" }}
              </div>
            </form>
          </div>
          <div class="panel-footer" style="overflow:hidden">
            <div class="pull-left">
              <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" id="paypalform">
                <input type="hidden" name="cmd" value="_xclick">
                <input TYPE="hidden" name="charset" value="utf-8">
                <input type="hidden" name="hosted_button_id" value="PM5MMZ7JL9EZC">
                <input type="hidden" name="business" value="appcodetraining@gmail.com">
                <input type="hidden" name="currency_code" value="THB">
                <input type="hidden" name="item_name" value="{{ book.name }}">
                <input type="hidden" id="_qty" name="quantity" value="0">
                <input type="hidden" id="_amount" name="amount" value="0">
                <input type="image" src="https://www.paypalobjects.com/th_TH/TH/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - วิธีชำระเงินแบบออนไลน์ที่ปลอดภัยกว่าและง่ายกว่า!">
              </form>
            </div>
            <a href="#" class="btn btn-success btn-lg pull-right" id="btnregister"><i class="fa fa-check"></i> สั่งซื้อหนังสือ</a>
          </div>
        </div>
        <a href="{% url 'book:detail' slug=book.slug %}" style="text-decoration:none"><i class="fa fa-chevron-left"></i> กลับหน้าที่แล้ว</a>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  function calPrice() {
    var qty = parseInt($('#qty').val(), 10);
    var price = parseFloat($('#price').val() || '0');
    return qty * price;
  }

  function formatNumber(v) {
    return v.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
  }

  function displayPrice() {
    var total = calPrice();
    $('#amount').val(total);
    $('#totallabel').html(formatNumber(total + ''));
  }

  $(function () {
    $('input[name="name"]').focus();
    displayPrice();

    $('#qty').on('change', function () {
      displayPrice();
    });

    $('#paypalform').on('submit', function () {
      $('#_qty').val($('#qty').val());
      $('#_amount').val($('#price').val());
    });

    $('#btnregister').on('click', function () {
      $('#unit').val($('#qty').val());
      $('#checkoutform').submit();
    });
  });
</script>
{% endblock %}

templates/book/detail.html
{% extends "master/base.html" %}
{% load humanize %}

{% block title %}หนังสือ | แอพโค้ด เทคโนโลยี จำกัด | สถาบันสอนเขียนโปรแกรม เรียนทำโมบายแอพ เรียนเว็บแอพลิเคชั่น เรียน IOT บริการอบรมทั้งในและนอกสถานที่{% endblock %}

{% block meta %}
<meta name="description" content="แอพโค้ด เทคโนโลยี, หนังสือ, คู่มือ, E-Book, หนังสือ{{ book.category.name }}, {{ book.name }}, {{ book.title }}">
<meta name="author" content="AppCode Technology Ltd., {{ book.teacher.name }}">
<meta name="keywords" content="หนังสือ, หนังสือเขียนโปรแกรม, คู่มือเขียนโปรแกรม, หนังสือคอมพิวเตอร์, E-Book, {{ book.tags.all|join:', ' }}">
<meta property="fb:app_id" content="520613538309239"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ book.name }}" />
<meta property="og:description" content="{{ book.title }}" />
<meta property="og:url" content="http://{{ request.get_host }}{{ request.get_full_path }}" />
{% if book.image %}
<meta property="og:image" content="http://{{ request.get_host }}{{ book.image.url }}" />
{% endif %}
{% endblock %}

{% block content %}
<div id="subnav" class="subnav-book">
  <div class="subnav-inner">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'book:index' %}">หนังสือ</a></li>
        <li class="active">{{ book.code }}</li>
      </ul>
      <h1>หนังสือ</h1>
    </div>
  </div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="course">
  <div class="container">
    <h1 style="margin-bottom:10px">{{ book.name }}</h1>
    <h4 style="margin-bottom:30px">{{ book.title }}<br><br><div class="fb-like" data-href="http://{{ request.get_host }}{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></h4>
    <div class="row">
      <div class="col-md-8">
        {% if book.code %}
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-3">
                {% if book.image %}
                <img src="{{ book.image.url }}" alt="{{ book.name }}" class="img-responsive">
                {% endif %}
              </div>
              <div class="col-md-9">
                <table class="table-book">
                  <tr>
                    <td>รหัสหนังสือ</td>
                    <td>{{ book.code }}</td>
                  </tr>
                  <tr>
                    <td>ประเภท</td>
                    <td>{{ book.category.name }}</td>
                  </tr>
                  <tr>
                    <td>ผู้เขียน</td>
                    <td>{{ book.teacher.fullname }}</td>
                  </tr>
                  <tr>
                    <td>จำนวนหน้า</td>
                    <td>{{ book.pages }}</td>
                  </tr>
                  <tr>
                    <td>ปีที่พิมพ์</td>
                    <td>{{ book.years }}</td>
                  </tr>
                </table>
                {% if book.example %}
                <hr>
                <h4>ดูสารบัญ และตัวอย่างบทแรก <a href="{{ book.example.url }}" target="_blank">คลิกที่นี่</a></h4>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        <!-- ./ book description -->
        {% if book.preview %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>คำนำ</strong>
            </div>
          </div>
          <div class="panel-body">
            <span>{{ book.preview }}</span>
          </div>
        </div>
        {% endif %}
        <!-- ./ book preview -->
        {% if accounts|length %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <strong>การชำระเงิน</strong>
            </div>
          </div>
          <div class="panel-body">
            <ul class="bank-list">
              {% for b in accounts %}
              <li>
                {% if b.image %}<img src="{{ b.image.url }}" alt="{{ b.bank }}">{% endif %}
                <span>{{ b.bank }} สาขา{{ b.branch }} บัญชี <strong>{{ b.acc_code }}</strong> {{ b.type }} {{ b.acc_name }}</span>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
        <!-- ./ book payment accounts -->
      </div>
      <div class="col-md-4">
        <ul class="radio-group">
          <li><label><input type="radio" name="type" data-value="paper" value="{{ book.price }}" checked> หนังสือเล่ม</label></li>
          <li><label><input type="radio" name="type" data-value="ebook" value="{{ book.price_ebook }}"> e-Book (PDF)</label></li>
        </ul>
        <div class="pricing">
          <h3>ราคา <span id="price"></span> บาท/เล่ม</h3>
        </div>
        <a href="#" id="btncheckout" class="btn btn-success btn-lg btn-block">สั่งซื้อหนังสือเล่มนี้</a>
        <div class="remark" id="qty">( จำนวนคงเหลือ {{ book.qty }} เล่ม )</div>
        {% if book.bookoption_set.count %}
        <div class="form-group">
          <h3>สิ่งที่มีมาด้วย</h3>
          <ul class="check-list">
            {% for o in book.bookoption_set.all %}
            <li><i class="fa fa-check"></i> {{ o.option }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ book options -->
        {% if book.teacher %}
        <div class="form-group">
          <h3>ผู้เขียน</h3>
          <div class="profile">
            <img src="{{ book.teacher.image.url }}" alt="{{ book.teacher.name }}">
            <div class="profile-item">
              <h4>{{ book.teacher.fullname }}</h4>
              <div class="caption">{{ book.teacher.position }}</div>
            </div>
          </div>
        </div>
        {% endif %}
        <!-- ./ book teacher -->
        {% if related_books|length %}
        <div class="form-group">
          <h3>หนังสือที่เกี่ยวข้อง</h3>
          <ul class="course-link">
            {% for r in related_books %}
            <li>
              <a href="{% url 'book:detail' slug=r.slug %}">
                <div class="item">
                  <strong>{{ r.name }}</strong>
                  <div class="subtext">
                    <span>จำนวน {{ r.pages }} หน้า / <strong>{{ r.price|floatformat:0|intcomma }} ฿</strong></span>
                  </div>
                </div>
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ book related -->
        {% if book.tags.count %}
        <div class="form-group">
          <h3>ป้ายกำกับ</h3>
          <ul class="tags">
            {% for t in book.tags.all %}
            <li><a href="{% url 'book:index' %}?tagid={{ t.id }}">{{ t.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ./ book tags list -->
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  function formatNumber(v) {
    return v.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
  }

  $(function () {
    $('#qty').show();
    $('#price').html(formatNumber($("input[name='type']:checked").val()));

    $("input[name='type']").on('click', function () {
      $('#price').html(formatNumber($(this).val()));
      if($(this).attr('data-value') == 'paper') {
        $('#qty').show();
      } else {
        $('#qty').hide();
      }
    });

    $('#btncheckout').on('click', function () {
      var obj = $('input[name="type"]:checked');
      var url = '{% url "book:checkout" slug=book.slug %}?type=' + obj.attr('data-value') + '&price=' + obj.val();
      window.location.href = url;
    });
  });
</script>
{% endblock %}